Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: com.example.capcafe.StreamLambdaHandler
      CodeUri: /Users/hamoos/Documents/Documents - Mohammed’s MacBook Air/AWS SA/capCafe
      Runtime: java17
      Architectures:
        - x86_64